### ISSUE TITLE
Opening UFOs in Trufont shows lots of empty glyphs named "glyph123" etc. 

### ISSUE THREAD

**Issue by madig** [daltonmaag/ubuntu#12]
Not sure where those are coming from.

**Comment by anthrotype** [comment]
the public.glyphOrder

originally from fontlab's encoding files which are nicely tabulated with those dummy placeholders

**Comment by madig** [comment]
Oh boy... so, is this a bug in Trufont or somewhere else?

**Comment by anthrotype** [comment]
it's not a bug... it's a feature :rocket:

**Comment by madig** [comment]
Trufont displaying them looks more like a bug than a feature :D are the
placeholders really needed?

**Comment by anthrotype** [comment]
No they aren’t needed

**Comment by moyogo** [comment]
This is normal.

**Comment by moyogo** [comment]
@madig the point of these is really to align meaningful glyphs. At the right size, you’ll have rows of 32 glyphs where these dummy glyphs are just there for padding the meaningful glyphs into nice columns.

**Comment by sladen** [comment]
@moyogo, that might be one of the _reasons_, but still doesn't explain where they _came from_ (what step or tool inserted them?—or are they leftovers from some starting "full unicode" template)

**Comment by madig** [comment]
And are they still "needed"? It's just cosmetics, but still.

**Comment by anthrotype** [comment]
Denis was talking about the glyphXXXX placeholders, which are cosmetic
The uniXXXX stuff should be removed if they are not in the font

**Comment by madig** [comment]
Eh... if I remove non-existing, non-glyphXXX names from the order, things don't line up anymore. Will send a PR that removes them all and see if someone complains.

**Comment by madig** [comment]
The UFO and GF version of Ubuntu-C actually contains the empty glyph127 😄

**Comment by moyogo** [comment]
@sladen we inserted them.

**Comment by sladen** [comment]
@moyogo, for the record, when? and how?

To what extent has their inclusion been found to be useful by (a) designers, (b) engineering.

**Comment by anthrotype** [comment]
ok so, when working in fontlab studio, people usually have custom encoding files *.enc, containing the list of glyph names for that font project.
Since FontLab allows to easily fit a font window to the desired row length, which defaults to 32, the common practice is to write these encoding files so that the rows are 32 glyph long and columns line up. E.g. the lowercase glyphs are placed immediately below the uppercase, etc. This helps greatly designers while they are drawing the glyphs.

These .enc files are made by duplicating some templates and customizing them manually in text editors.

When you apply an encoding file to a VFB inside FontLab, it will be embedded in the VFB itself, so next time you load the vfb the glyphs will be sorted accordingly (in the menu, the encoding name will show up as "imported" if I remember well).

The Fontlab-to-UFO export macro that DaMa uses internally, exports the content of the the fontlab font's encoding into the UFO glyphOrder, which is exactly meant for the same purpose: i.e. giving order to glyph names. And both need not contain all glyphs in the font, nor all glyph names in the encoding/glyphOrder need to be in the font.

For designers it's easier to maintiain a single enc file for multiple fonts belonging to a font project such as Ubuntu, even though some glyph cells will turn out to be empty for some fonts.

So these extra glyph names in the glyph order are there only to lay out the glyph cells in an ordered fashion in a font editor when the number of rows is 32. No more no less than that.
