### ISSUE TITLE
UFO normalization?

### ISSUE THREAD

**Issue by madig** [daltonmaag/ubuntu#13]
Opening and simply saving a UFO in Trufont will result in a complete reformatting of the entire UFO and huge commit churn. Other applications might format things differently. How about introducing a normalization step, like `psfnormalize` from https://github.com/silnrsi/pysilfont?

**Comment by anthrotype** [comment]
i believe it is already "normalized", but using https://github.com/unified-font-object/ufoNormalizer
@moyogo  can confirm

**Comment by moyogo** [comment]
Yes, the UFOs are normalized. We don’t mention how to do so nor do we have a Makefile target for it. We should definitely mention it.

**Comment by madig** [comment]
Will look into it, maybe even hook it into git. Would be nice if the normalizer would have a mode to explode at the first formatting error so I can quickly make a commit attempt fail and scream at the us— point out how to use the normalizer.

**Comment by anthrotype** [comment]
yes, I did something like that once, I wanted to use the ufonormalizer script as a pre-commit hook. Then I lost that patch somewhere in my stash :(

It needs lots of reworking because to use it as pre-commit hook you need something that normalizes (i.e. returns 0 if already normalized, or non-zero if it did change anything) every single file, rather than folder as a whole like it currently does.

I'll see what I can do (but no promises)

**Comment by sladen** [comment]
Can be returned to later when regular UFO-level commits start being a thing.
