### ISSUE TITLE
hdmx, LTSH, VDMX tables need to be added by hand

### ISSUE THREAD

**Issue by madig** [daltonmaag/ubuntu#6]
At the very least, it should be done by the Makefile.

Better yet, include the data in the source if that's possible. Second best option: write Python script to replace the exe you need to download.

**Comment by anthrotype** [comment]
a script that uses freetype-py to render all glyphs with bytecode interpreter activated, and compute these values and dumps them as TTX files in the UFO data folder, ready to be automatically merged by fontmake (via ufo2ft)

**Comment by madig** [comment]
Before I go off and cobble something together: is this metadata really needed? It's just precomputed data after all.

**Comment by anthrotype** [comment]
from the last time I tested this some time ago, the presence of the VDMX would make a difference for the line spacing on Windows GDI apps (Notepad), where it was used instead of the OS/2 winAscent winDescent. On Windows apps using DirectWrite the VDMX seemed to be ignored.

The main reason a VDMX would be needed is when delta instructions have been used to shift up the tallest glyphs e.g. accents that may clash on the x-eight at low sizes (or shift down the lowest glyphs for the same reason), which could create clipping in those apps that read WinAscent/WinDescent for line height. That is, if the WinAscent scaled for a given PPEM turns out to be smaller than the pixel height of the tallest glyph after applying TrueType instructions, then a pre-computed VDMX would override WinAscent/WinDescent for that PPEM by adding those extra pixels and avoiding the clipping.

This is only relevant for Windows. I believe FreeType doesn't read the VDMX, but maybe I'm wrong.

LTSH is completely useless.

hdmx is supposed to do the same as VDMX but for horizontal hinted metrics, but that has become even less relevant nowadays. I don't think the absence of hdmx would cause issues, but it'd be good to check especially with those glyphs that had their advance width or sidebearings modified by deltas.

**Comment by moyogo** [comment]
The tables are in the released fonts, we want to match the released fonts. If Canonical wants something else, it would be useful to know what it is.

**Comment by sladen** [comment]
In the medium-term it would be wonderful to drop whatever tables which can be proven to be not-useful.  (Benefits; file-size and maintainability).

To propose something is not useful through demonstrating it requires being able to deterministically build two near-identical copies.  One being a good known baseline, and second being the known baseline minus a specific table/change.  Then test, then make proposals.

So at the moment we should probably keep them in order help establish that goal of having a deterministically and mechanically buildable baseline equivalent to what the majority of users are presently using).

In the medium-/long-term perhaps somebody will make a proposal that they are not required, and we can test that at the time.

**Comment by madig** [comment]
A baseline for these tables can be achieved with https://github.com/daltonmaag/ubuntu/pull/32.

I'm leveraging wine and CacheTT.exe first so we can see if we can ditch the tables altogether. Not keen on implementing dead weight.

**Comment by madig** [comment]
Solved by https://github.com/daltonmaag/ubuntu/pull/32 for now. Reopen when this needs to be discussed again.
